site_name: שעה של שקט - Quiet Time
site_description: אתר המלצות לטובת הורים על ספרים, סרטים, משחקים ועוד - לפי גילאים
site_url: https://littlechoices.github.io

theme:
  name: material
  language: he
  direction: rtl
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: pink
      toggle:
        icon: material/brightness-7
        name: עבור למצב כהה
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: pink
      toggle:
        icon: material/brightness-4
        name: עבור למצב בהיר
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

plugins:
  - search:
      lang: he
  - tags

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

nav:
  - עמוד הבית: index.md
  - מחקרים: research.md
  - שיתוף תוכן: contribute.md
  - אודות: about.md

repo_url: https://github.com/dolby360/quiet_time.git
repo_name: dolby360/quiet_time

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dolby360/quiet_time.git
  
copyright: Copyright &copy; 2025 שעה של שקט - Quiet Time